/* automatically generated by rust-bindgen 0.72.1 */
#![allow(non_camel_case_types)]

pub type lbfgsfloatval_t = f64;
pub const LBFGS_SUCCESS: _bindgen_ty_1 = 0;
pub const LBFGS_CONVERGENCE: _bindgen_ty_1 = 0;
pub const LBFGS_STOP: _bindgen_ty_1 = 1;
pub const LBFGS_ALREADY_MINIMIZED: _bindgen_ty_1 = 2;
pub const LBFGSERR_UNKNOWNERROR: _bindgen_ty_1 = -1024;
pub const LBFGSERR_LOGICERROR: _bindgen_ty_1 = -1023;
pub const LBFGSERR_OUTOFMEMORY: _bindgen_ty_1 = -1022;
pub const LBFGSERR_CANCELED: _bindgen_ty_1 = -1021;
pub const LBFGSERR_INVALID_N: _bindgen_ty_1 = -1020;
pub const LBFGSERR_INVALID_N_SSE: _bindgen_ty_1 = -1019;
pub const LBFGSERR_INVALID_X_SSE: _bindgen_ty_1 = -1018;
pub const LBFGSERR_INVALID_EPSILON: _bindgen_ty_1 = -1017;
pub const LBFGSERR_INVALID_TESTPERIOD: _bindgen_ty_1 = -1016;
pub const LBFGSERR_INVALID_DELTA: _bindgen_ty_1 = -1015;
pub const LBFGSERR_INVALID_LINESEARCH: _bindgen_ty_1 = -1014;
pub const LBFGSERR_INVALID_MINSTEP: _bindgen_ty_1 = -1013;
pub const LBFGSERR_INVALID_MAXSTEP: _bindgen_ty_1 = -1012;
pub const LBFGSERR_INVALID_FTOL: _bindgen_ty_1 = -1011;
pub const LBFGSERR_INVALID_WOLFE: _bindgen_ty_1 = -1010;
pub const LBFGSERR_INVALID_GTOL: _bindgen_ty_1 = -1009;
pub const LBFGSERR_INVALID_XTOL: _bindgen_ty_1 = -1008;
pub const LBFGSERR_INVALID_MAXLINESEARCH: _bindgen_ty_1 = -1007;
pub const LBFGSERR_INVALID_ORTHANTWISE: _bindgen_ty_1 = -1006;
pub const LBFGSERR_INVALID_ORTHANTWISE_START: _bindgen_ty_1 = -1005;
pub const LBFGSERR_INVALID_ORTHANTWISE_END: _bindgen_ty_1 = -1004;
pub const LBFGSERR_OUTOFINTERVAL: _bindgen_ty_1 = -1003;
pub const LBFGSERR_INCORRECT_TMINMAX: _bindgen_ty_1 = -1002;
pub const LBFGSERR_ROUNDING_ERROR: _bindgen_ty_1 = -1001;
pub const LBFGSERR_MINIMUMSTEP: _bindgen_ty_1 = -1000;
pub const LBFGSERR_MAXIMUMSTEP: _bindgen_ty_1 = -999;
pub const LBFGSERR_MAXIMUMLINESEARCH: _bindgen_ty_1 = -998;
pub const LBFGSERR_MAXIMUMITERATION: _bindgen_ty_1 = -997;
pub const LBFGSERR_WIDTHTOOSMALL: _bindgen_ty_1 = -996;
pub const LBFGSERR_INVALIDPARAMETERS: _bindgen_ty_1 = -995;
pub const LBFGSERR_INCREASEGRADIENT: _bindgen_ty_1 = -994;
pub type _bindgen_ty_1 = ::std::os::raw::c_int;
pub const LBFGS_LINESEARCH_DEFAULT: _bindgen_ty_2 = 0;
pub const LBFGS_LINESEARCH_MORETHUENTE: _bindgen_ty_2 = 0;
pub const LBFGS_LINESEARCH_BACKTRACKING_ARMIJO: _bindgen_ty_2 = 1;
pub const LBFGS_LINESEARCH_BACKTRACKING: _bindgen_ty_2 = 2;
pub const LBFGS_LINESEARCH_BACKTRACKING_WOLFE: _bindgen_ty_2 = 2;
pub const LBFGS_LINESEARCH_BACKTRACKING_STRONG_WOLFE: _bindgen_ty_2 = 3;
pub type _bindgen_ty_2 = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lbfgs_parameter_t {
    pub m: ::std::os::raw::c_int,
    pub epsilon: lbfgsfloatval_t,
    pub past: ::std::os::raw::c_int,
    pub delta: lbfgsfloatval_t,
    pub max_iterations: ::std::os::raw::c_int,
    pub linesearch: ::std::os::raw::c_int,
    pub max_linesearch: ::std::os::raw::c_int,
    pub min_step: lbfgsfloatval_t,
    pub max_step: lbfgsfloatval_t,
    pub ftol: lbfgsfloatval_t,
    pub wolfe: lbfgsfloatval_t,
    pub gtol: lbfgsfloatval_t,
    pub xtol: lbfgsfloatval_t,
    pub orthantwise_c: lbfgsfloatval_t,
    pub orthantwise_start: ::std::os::raw::c_int,
    pub orthantwise_end: ::std::os::raw::c_int,
}
pub type lbfgs_evaluate_t = ::std::option::Option<
    unsafe extern "C" fn(
        instance: *mut ::std::os::raw::c_void,
        x: *const lbfgsfloatval_t,
        g: *mut lbfgsfloatval_t,
        n: ::std::os::raw::c_int,
        step: lbfgsfloatval_t,
    ) -> lbfgsfloatval_t,
>;
pub type lbfgs_progress_t = ::std::option::Option<
    unsafe extern "C" fn(
        instance: *mut ::std::os::raw::c_void,
        x: *const lbfgsfloatval_t,
        g: *const lbfgsfloatval_t,
        fx: lbfgsfloatval_t,
        xnorm: lbfgsfloatval_t,
        gnorm: lbfgsfloatval_t,
        step: lbfgsfloatval_t,
        n: ::std::os::raw::c_int,
        k: ::std::os::raw::c_int,
        ls: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
>;
unsafe extern "C" {
    pub fn lbfgs(
        n: ::std::os::raw::c_int,
        x: *mut lbfgsfloatval_t,
        ptr_fx: *mut lbfgsfloatval_t,
        proc_evaluate: lbfgs_evaluate_t,
        proc_progress: lbfgs_progress_t,
        instance: *mut ::std::os::raw::c_void,
        param: *mut lbfgs_parameter_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lbfgs_parameter_init(param: *mut lbfgs_parameter_t);
}
unsafe extern "C" {
    pub fn lbfgs_malloc(n: ::std::os::raw::c_int) -> *mut lbfgsfloatval_t;
}
unsafe extern "C" {
    pub fn lbfgs_free(x: *mut lbfgsfloatval_t);
}
unsafe extern "C" {
    pub fn lbfgs_strerror(err: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char;
}
